changelog:
  exclude:
    labels:
      - ignore-for-release        # 这些带标签的 PR 不进说明
    authors:
      - bot-account               # 排除某些机器人
  categories:
    - title: 🚀 Features
      labels:
        - enhancement
        - feat
    - title: 🐛 Fixes
      labels:
        - bug
        - fix
    - title: 🧹 Other Changes
      labels:
        - "*"                     # 兜底，未匹配到上面标签的 PR 都来这里
