server:
  servlet:
    context-path: /api


dir:
  beifen: ${daily.home:/home/user/snap/daily/beifen}
  db: beifen.db

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.sqlite.JDBC
    url: "jdbc:sqlite:${dir.beifen}/${dir.db}"
  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: always
      data-locations:  classpath:data.sql






mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl


# TODO  这些变量要可以被覆盖
email:
  enable: false
  config:
    from: wenzhuo4657@gmail.com
    to: wenzhuo4657@gmail.com
    password: ${GMAIL_PASSWORD}


